#!/bin/bash

# Clonando o repositório docker-sbt
git clone https://github.com/sbt/docker-sbt.git

# Navegando para o diretório do repositório clonado
cd docker-sbt

# Se houver dependências a instalar (por exemplo, se um arquivo requirements.txt for necessário), instale com pip
# pip install -r requirements.txt  # Descomente se houver requirements.txt

# Caso precise de outras instalações ou comandos após o clone, adicione-os aqui

